//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ch.rc
//
#define IDD_ABOUTBOX                    100
#define IDB_SPLASH                      102
#define IDD_DLG_COMMAND_VIEW            103
#define IDD_DLG_PROPERTY_DRAW           104
#define IDC_NODROP                      106
#define IDR_MAINFRAME                   128
#define IDR_CAD_POTYPE                  129
#define IDR_DRAWTOOLBAR                 130
#define IDR_MODIFYTOOLBAR               132
#define IDR_PROPERTYBAR                 134
#define IDR_TEMPLATE                    135
#define IDC_SELECT                      136
#define IDC_CURSOR1                     137
#define IDC_NONE                        137
#define IDI_ICON1                       151
#define IDC_CURSOR2                     152
#define IDC_DRAW                        152
#define IDC_CURSOR3                     154
#define IDD_DLG_COLORTOM                158
#define IDI_ICON2                       159
#define IDI_ICON3                       160
#define IDI_ICON4                       161
#define IDC_BREAK_TWO                   162
#define IDI_ICON5                       166
#define IDC_MBTN_MOVE                   168
#define IDD_DLG_MATRIX                  172
#define IDD_DLG_PARAM_GLASS_GRIND       173
#define IDR_PARAMETER                   175
#define IDD_DLG_PARAM_INOUT_KNIFE       177
#define IDD_DLG_PARAM_CLOTH_CUT         178
#define IDD_DLG_WORK_FOR                181
#define IDD_DLG_SENDFILE_NAME           184
#define IDR_GRIND_GLASS                 187
#define IDD_DLG_MILL_SIDE               190
#define IDD_DLG_ADD_RECT                191
#define IDD_DLG_PARALLEL                192
#define IDD_DLG_ADD_POINT               193
#define IDB_BITMAP_HORI                 200
#define IDB_BITMAP_VERT                 201
#define IDR_VIEW_BAR                    203
#define IDR_MENU_VIEW                   205
#define IDR_MENU_CILENT_RBTNDOW         209
#define IDC_RICHEDIT4                   1013
#define IDC_BUTTON1                     1014
#define IDC_BTN_CANCLE                  1014
#define IDC_BTN_FORWARD                 1014
#define IDC_BTN_MATRIX_OK               1014
#define IDC_BTN_PARAM1_OK               1014
#define IDC_BTN_SAVE_INOUT_KNIFE        1014
#define IDC_BTN_SAVE_WORK               1014
#define IDC_BTN_OK                      1015
#define IDC_BTN_BEHIND                  1015
#define IDC_BTN_MATRIX_NO               1015
#define IDC_BTN_PARAM1_CANCEL           1015
#define IDC_BTN_CANCLE_INOUT_KNIFE      1015
#define IDC_BTN_CANCLE_WORK             1015
#define IDC_BTN_INSERT_BEFORE           1016
#define IDC_BTN_INSERT_AFTER            1017
#define IDC_EDIT1                       1018
#define IDC_EDIT2                       1019
#define IDC_EDIT_COLORCB2               1019
#define IDC_EDIT3                       1020
#define IDC_EDIT_COLORCB3               1020
#define IDC_EDIT4                       1021
#define IDC_EDIT_COLORCB4               1021
#define IDC_EDIT5                       1022
#define IDC_EDIT_COLORCB5               1022
#define IDC_EDIT6                       1023
#define IDC_EDIT_COLORSB2               1023
#define IDC_EDIT7                       1024
#define IDC_EDIT_COLORSB3               1024
#define IDC_EDIT8                       1025
#define IDC_EDIT_COLORSB4               1025
#define IDC_STATIC1                     1026
#define IDC_EDIT_COLORSB5               1026
#define IDC_EDIT_OKNIFE_ARC_RADIUS      1026
#define IDC_STATIC2                     1027
#define IDC_EDIT_COLOR_MEAN2            1027
#define IDC_EDIT_OKNIFE_ARC_ANGLE       1027
#define IDC_STATIC3                     1028
#define IDC_EDIT_COLOR_MEAN3            1028
#define IDC_EDIT_OKNIFE_OVERLONG        1028
#define IDC_STATIC4                     1029
#define IDC_EDIT_COLOR_MEAN4            1029
#define IDC_STATIC5                     1030
#define IDC_EDIT_COLOR_MEAN5            1030
#define IDC_STATIC6                     1031
#define IDC_STATIC7                     1032
#define IDC_STATIC8                     1033
#define IDC_EDIT_COMMAND                1034
#define IDC_STATIC9                     1034
#define IDC_EDIT_REMIND                 1035
#define IDC_STATIC10                    1035
#define IDC_COMBO_COLOR                 1036
#define IDC_EDIT_COLORCB1               1037
#define IDC_EDIT_SEQUENCE               1037
#define IDC_EDIT_COLORSB1               1038
#define IDC_BTN_COLOR1                  1039
#define IDC_BTN_CUTDIR                  1039
#define IDC_BTN_COLOR2                  1040
#define IDC_EDIT_HORIZONTAL             1040
#define IDC_BTN_COLOR3                  1041
#define IDC_EDIT_VERITCAL               1041
#define IDC_BTN_COLOR4                  1042
#define IDC_EDIT_HORIZONTAL_OFFSET      1042
#define IDC_BTN_COLOR5                  1043
#define IDC_EDIT_VERITCAL_OFFSET        1043
#define IDC_EDIT_COLOR_MEAN1            1044
#define IDC_EDIT_CREATE_LONG            1044
#define IDC_EDIT_CREATE_WIDE            1045
#define IDC_CHECK_ROTATE_MOVE           1046
#define IDC_EDIT_YOUHUA_XMOVE           1047
#define IDC_EDIT_YOUHUA_YMOVE           1048
#define IDC_BTN_GET_LONG_WIDE           1049
#define IDC_EDIT_OVERCUT_ANGLE          1050
#define IDC_EDIT_OVERCUT_LONG           1051
#define IDC_EDIT_ROUGH_COUNT            1052
#define IDC_CHECK_IO_KNIFE_ISCENTER     1052
#define IDC_EDIT_SCALE_X                1052
#define IDC_EDIT_ROUGH_SIZE             1053
#define IDC_RADIO_IKNIFE_LINE_VERTICAL  1053
#define IDC_EDIT_SCALE_Y                1053
#define IDC_EDIT_PERFECT_COUNT          1054
#define IDC_RADIO_IKNIFE_LINE_TANGENT   1054
#define IDC_EDIT_CHAMFER                1054
#define IDC_EDIT_PERFECT_SIZE           1055
#define IDC_EDIT_MOVE_ORIGIN_X          1055
#define IDC_EDIT_POLISH_COUNT           1056
#define IDC_EDIT_SIMPLIFY               1056
#define IDC_EDIT_POLISH_SIZE            1057
#define IDC_RADIO_OKNIFE_LINE_VERTICAL  1057
#define IDC_EDIT_LESS_POINT_RADIUS      1057
#define IDC_EDIT_KNIFE_RADIUS           1058
#define IDC_RADIO_OKNIFE_LINE_TANGENT   1058
#define IDC_EDIT_MOVE_ORIGIN_Y          1058
#define IDC_BTN_IOKNIFE_COPY            1061
#define IDC_EDIT_DASH_SOLID             1061
#define IDC_EDIT_IKNIFE_LINE_LONGPERCENT 1062
#define IDC_EDIT_DASH_EMPTY             1062
#define IDC_EDIT_IKNIFE_LINE_LONG       1063
#define IDC_EDIT_IKNIFE_ARC_RADIUSPERCENT 1064
#define IDC_EDIT_IKNIFE_ARC_RADIUS      1065
#define IDC_EDIT_IKNIFE_ARC_ANGLE       1066
#define IDC_EDIT_MACHINE_SIZEY          1066
#define IDC_EDIT_OKNIFE_ARC_RADIUSPERCENT 1067
#define IDC_EDIT_OKNIFE_LINE_LONG       1068
#define IDC_EDIT_OKNIFE_LINE_LONGPERCENT 1069
#define IDC_RADIO1                      1070
#define IDC_RADIO_GLASSCUT              1070
#define IDC_RADIO_MILLSIDE_LEFT         1070
#define IDC_CMB_DAOBU                   1071
#define IDC_RADIO_GLASSGRIND            1071
#define IDC_RADIO_MILLSIDE_RIGHT        1071
#define IDC_RADIO_CLOTHCUT              1072
#define IDC_CMB_DIR_CLOCK1              1072
#define IDC_CHECK_NEED_OVERCUT1         1073
#define IDC_CMB_DIR_CLOCK2              1073
#define IDC_CHECK_NEED_OVERCUT2         1074
#define IDC_CMB_DIR_CLOCK3              1074
#define IDC_CHECK_NEED_OVERCUT4         1075
#define IDC_CMB_DIR_CLOCK4              1075
#define IDC_EDIT_FILE_SEND_PATHG        1075
#define IDC_CHECK_NEED_OVERCUT5         1076
#define IDC_EDIT_SEND_NAME              1076
#define IDC_CMB_DIR_CLOCK5              1076
#define IDC_EDIT_FILE_SEND_PATHDXF      1076
#define IDC_CHECK_NEED_OVERCUT3         1077
#define IDC_EDIT_MACHINE_SIZEX          1077
#define IDC_CHECK_SHOW_MACHINE_SIZE     1078
#define IDC_CHECK_SHOW_COORDINATE       1079
#define IDC_EDIT_MILLSIDE_DIS           1079
#define IDC_CHECK_SHOW_RULER_LINE       1080
#define ID_MILLSIDE_OK                  1080
#define ID_MILLSIDE_CANCEL              1081
#define ID_ADDRECT_OK                   1082
#define ID_ADDRECT_CANCEL               1083
#define IDC_EDIT_ADDRECT_TOP            1084
#define IDC_EDIT_ADDRECT_LEFT           1085
#define IDC_EDIT_PARALLEL_DIS           1085
#define IDC_EDIT_PARALLEL_HORI          1085
#define IDC_EDIT_ADDRECT_RIGHT          1086
#define ID_PARALLEL_OK                  1086
#define IDC_EDIT_ADDRECT_BOTTOM         1087
#define ID_PARALLEL_CANCEL              1087
#define IDC_CHECK_ROTATESYMMETRY_SAVEOLD 1088
#define IDC_EDIT_ADDRECT_RADIUS         1088
#define IDC_EDIT_PARALLEL_VERT          1088
#define IDC_EDIT_LONG_HORI              1089
#define IDC_EDIT_LONG_VERT              1090
#define ID_ADD_POINT_OK                 1091
#define ID_ADD_POINT_CANCEL             1092
#define IDC_CHECK_CHAMFER_LT            1093
#define IDC_CHECK_CHAMFER_LB            1094
#define IDC_CHECK_CHAMFER_RT            1095
#define IDC_CHECK_CHAMFER_RB            1096
#define IDC_BTN_CHIOCE_FILEPATH         1101
#define IDC_RADIO_LANGUAGE_CH           1102
#define IDC_RADIO_LANGUAGE_EN           1103
#define IDC_COMBO_CHAMFER_END_STYLE     1103
#define IDC_BTN_CHIOCE_FILEPATHG        1104
#define IDC_BTN_CHIOCE_FILEPATHDXF      1105
#define IDC_STATIC_KNIFE1               1105
#define IDC_STATIC_KNIFE2               1106
#define IDC_STATIC_KNIFE3               1107
#define IDC_STATIC_KNIFE4               1108
#define IDC_STATIC_KNIFE5               1109
#define IDC_RADIO_FILE_SEND_STYLEDXF    1114
#define IDC_RADIO_FILE_SEND_STYLEG      1115
#define IDC_CHECK_FILE_SEND_NAME_DEF    1116
#define ID_PROPERTY1                    12333
#define ID_LINE                         32765
#define ID_VERTICAL_LINE                32766
#define ID_POLYLINE                     32773
#define ID_RECTANGLE                    32774
#define ID_ROUNDARC                     32775
#define ID_ROUND                        32776
#define ID_SPLINE                       32777
#define ID_POINT                        32778
#define ID_ELLIPSE                      32779
#define ID_DELETE                       32780
#define ID_COPY                         32781
#define ID_MOVE                         32782
#define ID_MIRROR                       32783
#define ID_ROTATE                       32785
#define ID_BREAK_TWO                    32786
#define ID_RE_ARRANG                    32787
#define ID_OVER_CUT                     32788
#define ID_GRIND_GLASS                  42789
#define ID_SELECT_BEGIN_POS             32790
#define ID_IO_KNIFE                     32791
#define ID_SCALE                        32792
#define ID_TOGETHER                     32793
#define ID_SAVE_TO_FILE                 32794
#define ID_EXTEND_LINE                  32795
#define ID_CHAMFER                      32796
#define ID_MILL_GROOVES                 32797
#define ID_UNDO                         32798
#define ID_REDO                         32799
#define ID_MILL_SIDE                    32800
#define ID_TO_LESS_POINT                32801
#define ID_ADD_RECT                     32802
#define ID_MEASURE_LONG                 32803
#define ID_PARALLEL                     32804
#define ID_ADD_POINT                    32805
#define ID_DELETE_MORE_LINE             32806
#define ID_VIEW_MOVE                    32807
#define ID_VIEW_FULL                    32808
#define ID_MOVE_ORIGIN                  32809
#define ID_SCALE_XY                     32810
#define ID_SOLID_TO_DASH                32811
#define ID_TRIM                         32812
#define ID_MOVE_POINT                   32813
#define ID_MATRIX                       32814
#define ID_VIEW_COLOR                   32815
#define ID_VIEW_DRAW                    32816
#define ID_VIEW_MODIFY                  32817
#define ID_VIEW_PROPERTY                32818
#define ID_VIEW_PARAM                   32819
#define ID_VIEW_VIEW                    32820
#define ID_VIEW_TEMPLATE                32821
#define ID_VIEW_GRIND_GLASS             32822
#define ID_VIEW_COMMAND                 32835
#define ID_KONG                         32837
#define ID_ROTATE_180                   32853
#define ID_ROTATE_90                    32854
#define ID_SYMMETRY_XAXIS               32855
#define ID_SYMMETRY_YAXIS               32856
#define ID_SYMMETRY_LANDR               32857
#define ID_SYMMETRY_TANDB               32858
#define ID_ACCORDING_TO_LINE_HORI       32859
#define ID_ACCORDING_TO_LINE_VERT       32860
#define ID_ROTATE_ANGLE                 32870
#define IDW_LINEWIDTH                   32887
#define IDW_LINESTYLE                   32887
#define IDW_COLOR                       32888
#define ID_PARAM_IN_OUT_GRAPH           33000
#define ID_PARAM_JISAN                  43001
#define ID_PARAM_OVER_CUT               33002
#define ID_WORK_FOR                     33003
#define ID_PROPERTY                     33050
#define ID_SHOW_ARROW                   33051
#define ID_POINT_END                    33052
#define ID_POINT_NEAR                   33053
#define ID_ORTHOGONAL                   33054
#define ID_POINT_FOOT                   33055
#define ID_POINT_MID                    33056
#define ID_SHOW_NUM                     33100

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        210
#define _APS_NEXT_COMMAND_VALUE         32894
#define _APS_NEXT_CONTROL_VALUE         1117
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
